# Site Settings
lang: pt
title: Martita.Art
author: "Marta Gomes"
#tagline: Martita
email: martita@martita.art
description: "Trabalhos de Patchwork"
baseurl: ""
url: "https://martita.art"
google_analytics: UA-220776159-1
permalink: pretty
enhanced_favicon: true
logo: "/img/logo.png"
hide_share_buttons: true
theme_color: "#F9C0C0"
fixed_navbar: top
social: true

admin_info:
  name: CGomesu
  url: https://cgomesu.com
  email: admin@martita.art

#paginate: 5
#paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
#  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Marta Gomes"
      layout: post
      show_sidebar: true

markdown: kramdown
highlighter: rouge

# Uncomment and edit to include footer menu to the bottom of each page
footer_menu: footer_menu

collections:
  produtos:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
